version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: API-REST/Dockerfile
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./API-REST/src:/usr/src/app/src
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ugaUGA#123
      - DB_NAME=dbsenac
    command: [ "npm", "run", "dev" ]

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ugaUGA#123
      MYSQL_DATABASE: dbsenac
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
